.TH MISTRAL_SET_CALL_TYPE_NAME 3 2016-06-16 Ellexus "Mistral Plug-in Programmer's Manual"
.SH NAME
mistral_set_call_type_name \- Function called to initialise a
standardised string representation of the passed call type mask
.SH SYNOPSIS
.nf
.B #include """mistral_plugin.h"""
.sp
.BI "void mistral_set_call_type_name(uint32_t " mask ");"
.fi
.SH DESCRIPTION
By default the \fImistral_call_type_names\fP array is sparsely populated
with translations of any call type masks seen in log messages.
This function can be called to populate the array with the translation
of an arbitrary call type mask.
.LP
The value of \fImask\fP must be less than \fICALL_TYPE_MASK_MAX\fP, all
other values will be silently ignored. 
.sp
.SH "SEE ALSO"
\fI"mistral_plugin.h"\fP, \fBmistral_startup\fP(3)

